### ISSUE TITLE
Switch to `mpl-pan-zoom` to get widgetlocking behavior

### ISSUE THREAD

**Issue by ianhi** [European-XFEL/DAMNIT#10]
Hi all, and perhaps in particular @JamesWrigley 

I saw these lines:
https://github.com/European-XFEL/DAMNIT/blob/4f17375165031c4f6f4a8ea2035777035fdae83d/damnit/gui/plot.py#L66-L76

and wanted to pop in and say that if you transition to using [`mpl-pan-zoom`](https://mpl-pan-zoom.readthedocs.io/en/latest/) which is the dedicated package where zoom_factory and panning behavior will live long term then I think the iwdget locking behavior is fixed by this PR: https://github.com/mpl-extensions/mpl-pan-zoom/pull/2

n.b. `panhandler` -> `PanManager` when switching the packages.

**Comment by JamesWrigley** [comment]
Great, thank you very much for the hint and for your work :)
