### ISSUE TITLE
'reprocess all' is confusing

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/DAMNIT#129]
FXE just got bitten by this: they set up DAMNIT for a proposal which already has runs, and then ran `amore-proto reprocess all`, expecting it to process all the existing runs. Reprocessing specific run numbers can add them, but `all` only means all the runs DAMNIT already knows about, which in this case is 0 runs.

Workaround: specify the run numbers, e.g. `amore-proto reprocess $(seq 2 77)`

An easy improvement would be a 'did you mean' message when there are 0 runs. Going further, we might consider turning `reprocess` into `process`, where `all` would logically mean 'all the runs in the proposal'. We could add ways to reprocess all the runs already in DAMNIT, or to only process runs not already in DAMNIT.

**Comment by JamesWrigley** [comment]
Possible duplicate: #87

**Comment by takluyver** [comment]
D'oh. Yes, that's basically the same. Should have searched before I wrote this. Thanks!
