### ISSUE TITLE
API to access the data in the table and HDF5 files

### ISSUE THREAD

**Issue by JamesWrigley** [European-XFEL/DAMNIT#33]
DAMNIT stores the full data from variables in HDF5 files, and reduced data and comments/user-defined variables in the SQLite database. This was always intended to be made available to users, but right now there's no API for it (albeit some users have gone to the lengths of creating their own API). See this Zulip stream for previous discussions: https://euxfel-da.zulipchat.com/#narrow/stream/323938-AMORE/topic/APIs

**Comment by CammilleCC** [comment]
The current API is in: https://github.com/European-XFEL/DAMNIT/blob/master/damnit/backend/api.py

Thomas would like to revisit and have a look
