### ISSUE TITLE
Propagate GUI changes to other GUIs

### ISSUE THREAD

**Issue by JamesWrigley** [European-XFEL/DAMNIT#47]
The PyQt GUI is right now somewhat independent. If two GUIs are open and one of them edits a comment the other GUI won't display the updated value, which is confusing and we should fix that. Partially implemented in b416f7e.

@CammilleCC, do you have any idea how this would work with the web GUI? Websockets or something? My implementation uses Kafka but that's probably not we want in the future :thinking:

**Comment by CammilleCC** [comment]
We're checking GraphQL out, which uses websockets under the hood. I agree that Kafka is not the best communication protocol between webservers and webclients.

**Comment by JamesWrigley** [comment]
This was fixed in #226.
